### ISSUE TITLE
[DOC] <></> & Fragement

### ISSUE THREAD

**Issue by RyuK-H** [anxiubin/to-do-list#1]
제가 오해를 하고 있었던 부분이였는데.

`<></>` 로 공백의 태그 생성시 div 태그가 생성된다라고 오해를 하고 있었습니다.
검색해보니,  `<></>` 태그 생성시 별다른 태그가 생성되지 않고 묶이는 것으로 알게 되었습니다. [(React 단축 문법)](https://ko.reactjs.org/docs/fragments.html#short-syntax)

Fragement와 <></> 차이는 key를 입력할 수 있고 없고 입니다.

```
function Glossary(props) {
  return (
    <dl>
      {props.items.map(item => (
        // React는 `key`가 없으면 key warning을 발생합니다.
        <React.Fragment key={item.id}>
          <dt>{item.term}</dt>
          <dd>{item.description}</dd>
        </React.Fragment>
      ))}
    </dl>
  );
}
```

위 항목에서 `React.Fragment` 대신 <></> 를 사용하게 될 때, 해당 컴포넌트에 key값을 넣어줄 수 없기 때문에 React에서는 경고를 출력 할 것입니다.

반복문을 통해 태그에 key값을 직접 넣어주어야 할 경우 <></>가 아닌, <Fragement>를 사용해야하고,
그 외 별다른 차이는 없는 것 같습니다.

제가 코드리뷰 드린 부분은 잘 못된 부분이였네용! 스마미셍

**Comment by anxiubin** [comment]
아~ 그러면 컴포넌트에 key값을 넣어줘야할 때는 <></> 대신 <React.Fragment></React.Fragment>를 사용하면 되겠군요! 감사합니당
